### PR TITLE
feat: onboarding

### PR DESCRIPTION
**Pull request by dexturr**
## Feature onboarding

Closes https://github.com/vegaprotocol/vegawallet-browser/issues/119
Closes https://github.com/vegaprotocol/vegawallet-browser/issues/123
Closes https://github.com/vegaprotocol/vegawallet-browser/issues/127
Closes https://github.com/vegaprotocol/vegawallet-browser/issues/145

https://user-images.githubusercontent.com/26136207/236415957-a882397b-f467-464f-b724-82169f8f874a.mov

### CODE REVIEW

**Review by edd — COMMENTED** [review]
Code-wise it looks fine, just having a quick run through ⌛

**Review by edd — COMMENTED** [review]
**nitpick (non-blocking)**: One minor layout change - the tick being vertically centred on the label looks odd.

Screenshot 2023-05-05 at 15 15 59

**Review by edd — APPROVED** [review]

**Review by sam-keen — APPROVED** [review]

**Comment by dalebennett1992** [comment]
So I have a few questions and something that I believe is a small bug.

**Bug:** I do not have to click in the checkbox to accept it. I can click anywhere in the area I have marked out below
image

This applies to both the password and recovery phrase checkbox,

**Questions and suggestions**
1. One of the AC items is 'I am given feedback that my wallet was successfully created'
My assumption is that there would be a little message after creation to indicate success. Instead it shows the view wallet page after. You can see your wallet here though of course. Just checking that this is the intended way of satisfying this AC

2. Similar to point 1, we have an AC item stating 'When I have submitted my new password, I am given some feedback that it was set successfully', there is no actual feedback other than there being a create/import wallet screen. I assumed there would be some kind of success message, so again, are we happy with this for now or do we add something in to satisfy the AC?

3. I saw @edd make a point about the tick being vertically centred, I agree with his point but I also think the same can be said of our checkboxes. super minor but should we align this with the first line of the message the checkbox is associated with?

So instead of this..
image

You would have this.. (done in paint so sorry if it is out of whack ;)
image

So that would apply to the password warning checkbox and also the recovery phrase checkbox

4. So this one is super picky. Copy to clipboard looks to be placed slightly below the key here to my eyes. I know you have to really look to see it so the difference must only be a couple of pixels but thought I'd mention as I have seen it now haha.
image

**Comment by dalebennett1992** [comment]
also @emilbayes / @dexturr reckon we could get those backend tests passing before this goes down. I also have some more test changes ready for review which I will chuck into slack in a sec

**Comment by dexturr** [comment]
> So I have a few questions and a couple of small bugs.
> 
> **Bug:** I do not have to click in the checkbox to accept it. I can click anywhere in the area I have marked out below image
> 
> This applies to both the password and recovery phrase checkbox
> 
> **Bug**: The wallets and settings text in the nav panel is misaligned- this is in **firefox** image
> 
> **Questions and suggestions**
> 
> 1. One of the AC items is 'I am given feedback that my wallet was successfully created'
>    My assumption is that there would be a little message after creation to indicate success. Instead it shows the view wallet page after. You can see your wallet here though of course. Just checking that this is the intended way of satisfying this AC
> 2. Similar to point 1, we have an AC item stating 'When I have submitted my new password, I am given some feedback that it was set successfully', there is no actual feedback other than there being a create/import wallet screen. I assumed there would be some kind of success message, so again, are we happy with this for now or do we add something in to satisfy the AC?
> 3. I saw @edd make a point about the tick being vertically centred, I agree with his point but I also think the same can be said of our checkboxes. super minor but should we align this with the first line of the message the checkbox is associated with?
> 
> So instead of this.. image
> 
> You would have this.. (done in paint so sorry if it is out of whack ;) image
> 
> So that would apply to the password warning checkbox and also the recovery phrase checkbox
> 
> 4. So this one is super picky. Copy to clipboard looks to be placed slightly below the key here to my eyes. I know you have to really look to see it so the difference must only be a couple of pixels but thought I'd mention as I have seen it now haha.
>    image

> I do not have to click in the checkbox to accept it. I can click anywhere in the area I have marked out below

Intended

>? I saw @edd make a point about the tick being vertically centred, I agree with his point but I also think the same can be said of our checkboxes. super minor but should we align this with the first line of the message the checkbox is associated with?

UI toolkit changes are tracked by this ticket: https://github.com/vegaprotocol/vegawallet-browser/issues/160. I have added it but I don't think it's a thing for this PR. Because of the dev ex of these things it's best if we batch them.

The UX/AC questions I have raised in a slack message.

So that leaves us TODO:

- [ ] Firefox mis alignment
- [ ] Any actions based on the UX/AC conversation
- [ ] Double check alignment of copy icon

**Review by dalebennett1992 — APPROVED** [review]

**Pull request merged**
