### PR TITLE
Feat/multi network

### LINKED ISSUE #677: Adjust disclaimers on the new wallets
## Chore

I think we can make the mainnet disclaimer applicable to both networks and versions, and make sure there’s a small additional notice on the canary build about it being a pre-release version and the risks of that, especially on mainnet.

## Tasks

- [ ] Update main wallet 
- [ ] Update canary wallet

### LINKED ISSUE #695: Interim multi-network support
## Chore

Front end work to close out the interim solution for multinetwork support.

## Tasks

- [ ] 
- [ ] 
- [ ]

### PR DESCRIPTION
**Pull request by dexturr**
Closes #677 
Closes #695

### CODE REVIEW

**Comment by daro-maj** [comment]
link for docs does not work for fairground and mainnet
image

**Comment by daro-maj** [comment]
Why do we have linked nodes if each one returns an error ?

image

**Comment by daro-maj** [comment]
We have error during switch margin mode

image

`Error: Market with id a79834ef7d9019a60821d4962fc2561663a2558011dc9ed972ab8b01381e8d10 not found
    at getMarketById (chrome-extension://niochpahfbnajmdfmbnekhajmhofchog/popup.js:109461:20)
    at VegaMarket (chrome-extension://niochpahfbnajmdfmbnekhajmhofchog/popup.js:111022:21)
    at renderWithHooks (chrome-extension://niochpahfbnajmdfmbnekhajmhofchog/popup.js:24368:20)
    at updateFunctionComponent (chrome-extension://niochpahfbnajmdfmbnekhajmhofchog/popup.js:27646:22)
    at beginWork (chrome-extension://niochpahfbnajmdfmbnekhajmhofchog/popup.js:29659:18)
    at beginWork$1 (chrome-extension://niochpahfbnajmdfmbnekhajmhofchog/popup.js:35469:16)
    at performUnitOfWork (chrome-extension://niochpahfbnajmdfmbnekhajmhofchog/popup.js:34603:14)
    at workLoopSync (chrome-extension://niochpahfbnajmdfmbnekhajmhofchog/popup.js:34509:7)
    at renderRootSync (chrome-extension://niochpahfbnajmdfmbnekhajmhofchog/popup.js:34477:9)
    at recoverFromConcurrentError (chrome-extension://niochpahfbnajmdfmbnekhajmhofchog/popup.js:33894:22)`

**Comment by dexturr** [comment]
> We have error during submit an order and switching the margin mode
> 
> image
> image
> 
> `Error: Market with id a79834ef7d9019a60821d4962fc2561663a2558011dc9ed972ab8b01381e8d10 not found at getMarketById (chrome-extension://niochpahfbnajmdfmbnekhajmhofchog/popup.js:109461:20) at VegaMarket (chrome-extension://niochpahfbnajmdfmbnekhajmhofchog/popup.js:111022:21) at renderWithHooks (chrome-extension://niochpahfbnajmdfmbnekhajmhofchog/popup.js:24368:20) at updateFunctionComponent (chrome-extension://niochpahfbnajmdfmbnekhajmhofchog/popup.js:27646:22) at beginWork (chrome-extension://niochpahfbnajmdfmbnekhajmhofchog/popup.js:29659:18) at beginWork$1 (chrome-extension://niochpahfbnajmdfmbnekhajmhofchog/popup.js:35469:16) at performUnitOfWork (chrome-extension://niochpahfbnajmdfmbnekhajmhofchog/popup.js:34603:14) at workLoopSync (chrome-extension://niochpahfbnajmdfmbnekhajmhofchog/popup.js:34509:7) at renderRootSync (chrome-extension://niochpahfbnajmdfmbnekhajmhofchog/popup.js:34477:9) at recoverFromConcurrentError (chrome-extension://niochpahfbnajmdfmbnekhajmhofchog/popup.js:33894:22)`

Is tracked by this ticket: https://github.com/vegaprotocol/vegawallet-browser/issues/625

**Review by daro-maj — APPROVED** [review]

**Pull request merged**
